# Generated by Django 4.2 on 2024-05-31 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("users", "0001_initial"),
        ("programs", "0001_initial"),
        ("members", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="mentees",
            field=models.ManyToManyField(
                related_name="teams", through="members.Member", to="users.mentee"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="mentor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentor_teams",
                to="users.mentor",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="programs.program",
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["name"], name="teams_team_name_43e047_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["program"], name="teams_team_program_97300e_idx"
            ),
        ),
    ]
