# Generated by Django 4.2 on 2024-05-31 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="team",
            name="teams_team_program_97300e_idx",
        ),
        migrations.RemoveField(
            model_name="team",
            name="program",
        ),
    ]
