# Generated by Django 4.2 on 2024-05-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_is_mentee_customuser_is_mentor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_mentee",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_mentor",
        ),
    ]
