name = "csoc_backend"
main = "src/index.ts"
compatibility_date = "2023-12-01"
account_id = "7c6f21d131452cb899ffb5d1b7f81f28"

[[d1_databases]]
binding = "CSOC_DB"
database_name = "csoc-db-25"
database_id = "9ca9f6b5-2547-4be7-8cea-b957bb7da0f0"
migrations_dir = "migrations"
