# Generated by Django 4.2 on 2024-05-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="description",
            field=models.CharField(max_length=128),
        ),
    ]
