# Generated by Django 4.2 on 2024-05-31 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("teams", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="mentee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="users.mentee",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="teams.team",
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["mentee"], name="members_mem_mentee__963a73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["team"], name="members_mem_team_id_dd8520_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["accepted"], name="members_mem_accepte_d89266_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="member",
            unique_together={("mentee", "team")},
        ),
    ]
