# Generated by Django 4.2 on 2024-05-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="member",
            name="members_mem_accepte_d89266_idx",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="accepted",
            new_name="already_accepted",
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["already_accepted"], name="members_mem_already_221d20_idx"
            ),
        ),
    ]
